#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0


#
# Schema version of the content. Used by the SDK to apply the corresponding parsing rules.
#
version: 1.0.0

# server 所用到配置部分设置
server:
  restful:
    listenAddress: :9999
################################################################################
#
#   Database Configuration
#   - database to store blockchain information data
#
################################################################################
Database:
  Enabled: true
  Driver: mysql
  Address: 114.67.79.102:3306
  DBname: go_kass
  User: root
  Password: 12345